[default]
ssl_crt_file = "/ssl/ssl.crt"
ssl_key_file = "/ssl/ssl.key"

[[http_d]]
server_name = "www.port.error"
upstream = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.http.only"
listen = 18000
upstream = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.https.only"
listen_ssl = 10443
ssl_file = "/ssl/file"
upstream = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.example.com"
listen = 18000
listen_ssl = 10443
upstream = "http://127.0.0.1:8000"
client_max_body_size = "100m"

[[http_d]]
server_name = "www.custom.root.location.com"
listen_ssl = 10443
upstream = "http://127.0.0.1:8000"
location."/" = """
proxy_pass $upstream;
"""

[[http_d]]
server_name = "www.more.location.com"
listen_ssl = 10443
upstream = "http://127.0.0.1:8000"
location."/" = """
proxy_pass $upstream;
"""
location."/api/verify" = """
proxy_pass $upstream;
"""

[[stream_d]]
comment = "ssh"
listen = 22
upstream = "192.168.1.1:22"