[default]
ssl_cert_domain = "www.example.com"

[[http_d]]
server_name = "www.port.error"
proxy_pass = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.http.only"
listen = 18000
proxy_pass = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.https.only"
listen_ssl = 10443
proxy_pass = "http://127.0.0.1:8000"

[[http_d]]
server_name = "www.example.com"
listen = 18000
listen_ssl = 10443
proxy_pass = "http://127.0.0.1:8000"
client_max_body_size = "100m"

[[http_d]]
server_name = "www.custom.root.location.com"
listen_ssl = 10443
proxy_pass = "http://127.0.0.1:8000"
location."/" = """
proxy_pass $proxy_pass;
"""

[[http_d]]
server_name = "www.more.location.com"
listen_ssl = 10443
proxy_pass = "http://127.0.0.1:8000"
location."/" = """
proxy_pass $proxy_pass;
"""
location."/api/verify" = """
proxy_pass $proxy_pass;
"""

[[http_d]]
server_name = "www.mapping.root.com"
listen_ssl = 10443
root = "/var/www"

[[stream_d]]
comment = "ssh"
listen = 22
proxy_pass = "192.168.1.1:22"