[default]
ssl_cert_domain = "example.com"

[[http_d]]
server_name = "www.example.com"
listen = 10080
listen_ssl = 10443
proxy_pass = "http://127.0.0.1:8000"

[[stream_d]]
comment = "ssh"
listen = 10022
proxy_pass = "192.168.1.1:22"
