# CLI
DEFAULT_CONFIG_NGINX_TOML = "/config/nginx.toml"

DEFAULT_NGINX_CONF_DIR = "/data/nginx"
DEFAULT_NGINX_HTTP_CONF = "http.conf"
DEFAULT_NGINX_HTTP_DEFAULT_CONF = "http_default.conf"
DEFAULT_NGINX_STREAM_CONF = "stream.conf"

# NGINX
DEFAULT_SSL_FILE_DIR = "/data/dnsrobocert/live"

DEFAULT_HTTP_PORT = 10080
DEFAULT_HTTPS_PORT = 10443
